Spring:
  datasource: # mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.158.9:3306/yanyan?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: yanyan
    password: yanyan
    type: com.alibaba.druid.pool.DruidDataSource
  data: # redis配置
    redis:
      host: 119.3.158.9
      password: redis
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
logging:
  level:
    com.yanyan: debug