Spring:
  application:
    name: 研研网
  datasource: # mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.158.9:3306/yanyan?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: yanyan
    password: yanyan
    type: com.alibaba.druid.pool.DruidDataSource
  data: # redis配置
    redis:
      host: 119.3.158.9
      password: redis
      lettuce:
        pool:
          max-active: 20
          max-idle: 20
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 0
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  ai:
    openai:
      api-key: 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
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    com.yanyan: debug
server:
  tomcat:
    max-swallow-size: 100MB