Spring:
  application:
    name: 研研网
  datasource: # mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/yanyan?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: #username
    password: #password
    type: com.alibaba.druid.pool.DruidDataSource
  data: # redis配置
    redis:
      host: #redis服务器地址
      password: #redis服务器root账户密码
      lettuce:
        pool:
          max-active: 20
          max-idle: 20
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 4 #数据库
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  ai:
    openai:
      api-key: #chatgpt api-key
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    com.yanyan: debug
server:
  tomcat:
    max-swallow-size: 100MB
web:
  upload-path: /root/yanyan/images/
