---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 韶光善良君.
--- DateTime: 2024/5/13 10:38
---
-- 检查组是否存在
-- EXISTS stream.mq.server
if redis.call('EXISTS', 'stream.mq.server')==0 then
    -- 创建组
    -- XGROUP CREATE stream.mq.server g1 0 MKSTREAM
    redis.call('XGROUP', 'CREATE', 'stream.mq.server', 'g1', '0', 'MKSTREAM')
end
return 0