---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 韶光善良君.
--- DateTime: 2024/5/9 3:29
---
-- 1.参数列表
-- 1.1.uuid
local uuid = ARGV[1]
-- 1.2.文件路径
local fileUrl = ARGV[2]

-- 3.6.发送消息到队列中， XADD stream.orders * k1 v1 k2 v2 ...
redis.call('xadd', 'stream.mq.server', '*', 'uuid', uuid, 'file_url', fileUrl)
return 0